### PR TITLE
Upgrade to blang/semver/v4 v4.0.0

### PR DESCRIPTION
**Pull request by skitt**
This is the first version to be fully go-mod-compatible.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
Looks like it is only used in the package validator. I think kubeadm is not running the package checks at least.

Are you using this library and saw a problem due to the semver library not being at v4?

**Comment by skitt** [comment]
> Looks like it is only used in the package validator. I think kubeadm is not running the package checks at least.
> 
> Are you using this library and saw a problem due to the semver library not being at v4?

Not directly; this is for consistency with https://github.com/kubernetes/kubernetes/pull/108629, to clean up the dependency tree of dependencies further down from Kubernetes (where we end up with both version 3.5.1 and 4.0.0 of `semver`).

**Comment by neolit123** [comment]
/ok-to-test

Ok that is fair, given k/k is the main user but this lib will have to be bumped with a new release and revendored in k/k.

There is already one MINOR level feature pending release. Releases of this lib happen close before code freeze of a k/k release (pending).

If there was nothing else commited we could have made a patch with the semver bump.

**Comment by neolit123** [comment]
/lgtm
/approve

i should keep a note to release a new version of this repository before the 30th of march (code freeze for k8s 1.24).

**Comment by skitt** [comment]
> i should keep a note to release a new version of this repository before the 30th of march (code freeze for k8s 1.24).

Gentle reminder about this so there’s time to merge the bump in k/k itself...

**Comment by neolit123** [comment]
had a todo for next week, but i guess i can push the release today.
don't think anything new will land here before the k8s CF.

**Comment by skitt** [comment]
Thanks!

**Pull request merged**
