### PR TITLE
PidLimits promoted to GA

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
Follow up from https://github.com/kubernetes/kubernetes/pull/94140

### CODE REVIEW

**Comment by neolit123** [comment]
Thanks! Lets hold this until the feature PR merges.

This also means we have to release a new Minor of this library and revendor it in k/k.

/lgtm
/approve
/hold

**Comment by SergeyKanzhelev** [comment]
PR in k/k got merged. I wonder if I can cancel hold on self-authored PR...

/hold cancel

**Comment by neolit123** [comment]
@SergeyKanzhelev do you happen to know if there are other planned features from SIG node related to this repository?

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev do you happen to know if there are other planned features from SIG node related to this repository?

I don't think so after briefly looking thru the code. even for this change, cutting release is not critical as it is not a breaking change. So perhaps, this can wait in case something else will come up

**Comment by neolit123** [comment]
ok, since this library's "release process" is a bit bottlenecked on my availability, i'd prefer if we cut the release now and re-vendor in k/k right away to unblock tests if needed(?).

we cut more releases here if needed for 1.20.

**Comment by neolit123** [comment]
here is the new release:
https://github.com/kubernetes/system-validators/releases/tag/v1.2.0

would you be able to send the PR to re-vendor?

here is an example commit on how we update the vendor:
https://github.com/kubernetes/kubernetes/commit/8183787493472b2d9a7006f78da63cd589456f81

it uses the script:
https://github.com/kubernetes/kubernetes/blob/master/hack/pin-dependency.sh

**Comment by SergeyKanzhelev** [comment]
> here is the new release:
> https://github.com/kubernetes/system-validators/releases/tag/v1.2.0
> 
> would you be able to send the PR to re-vendor?

Yes, thank you for the detailed instructions!

**Pull request merged**
